---
driver:
  name: docker
platforms:
  - name: ansible-role-nodejs-1404
    image: ubuntu:14.04

  - name: ansible-role-nodejs-1604
    image: ubuntu:16.04

lint:
  name: yamllint
  enabled: False

provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        nodejs_install_npm_user: root
        nodejs_npm_global_packages:
          - name: less
